### ISSUE TITLE
WDtagger does not work

### ISSUE THREAD

**Issue by moon47usaco** [zamp/vid2vid#13]
Trying to replace the pos prompt with WD tagger will not work.

```
Executing pass: RenderPass (comfyui)
Traceback (most recent call last):
  File "S:\Ai\Repos\vid2vid\main.py", line 110, in <module>
    main()
  File "S:\Ai\Repos\vid2vid\main.py", line 86, in main
    processors.process_comfyui(rp_config, config, emotion_tokens)
  File "S:\Ai\Repos\vid2vid\processors.py", line 102, in process_comfyui
    run_stable_diffusion(input_dir+file, video_dir+file, output_dir+file, config, extra_config, get_tokens_for_frame(frame, emotion_tokens))
  File "S:\Ai\Repos\vid2vid\processors.py", line 17, in run_stable_diffusion
    image = comfyui.process_image(input_file_path, src_file_path, config, extra_config, emotion_tokens)
  File "S:\Ai\Repos\vid2vid\comfyui.py", line 92, in process_image
    workflow_json = json.load(open(workflow))
  File "C:\Users\moon4\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\moon4\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 6782: character maps to <undefined>

S:\Ai\Repos\vid2vid>pause
```
![Screenshot 2023-09-27 003432](https://github.com/zamp/vid2vid/assets/15712871/b39544f6-aad3-4d4c-8758-8adf2adbb431)

**Comment by axb2035** [comment]
I haven't been able to repeat this bug, but I suspect it is related to the funky snake emoji in the title of the node. It looks like it is failing to decode a character when loading the workflow .json file. 

As a workaround try editing the title of the node to be just "WD14 Tagger" and see if it works.
